name: Deploy to EC2

on:
  push:
    branches:
      - main


jobs:

  # -----------------------------
  # Job 1: Terraform Infrastructure
  # -----------------------------
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    outputs:
      ec2_ip: ${{ steps.get_ip.outputs.ip }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        working-directory: terraform
        run: terraform init


      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan


      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve


      - name: Get EC2 Public IP
        id: get_ip
        working-directory: terraform
        run: |
          echo "ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT



  # -----------------------------
  # Job 2: Deploy Application
  # -----------------------------
  deploy:

    name: Deploy Docker Application

    runs-on: ubuntu-latest

    needs: terraform


    steps:


      - name: Wait for EC2
        run: sleep 60



      - name: Deploy to EC2

        uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ needs.terraform.outputs.ec2_ip }}

          username: ${{ secrets.EC2_USER }}

          key: ${{ secrets.SSH_PRIVATE_KEY }}


          script: |

            set -e


            echo "Waiting for Docker..."


            until command -v docker >/dev/null 2>&1
            do
              echo "Docker not installed yet..."
              sleep 10
            done


            until sudo systemctl is-active --quiet docker
            do
              echo "Waiting for Docker service..."
              sleep 5
            done


            echo "Docker ready"



            #############################################
            # Clone repository
            #############################################

            if [ ! -d "/home/ubuntu/devops" ]; then

              cd /home/ubuntu

              git clone https://github.com/Vinuthads/devops.git

            fi



            cd /home/ubuntu/devops



            git pull origin main



            #############################################
            # Start application containers
            #############################################

            echo "Starting containers"


            sudo docker compose up --build -d



            echo "Waiting for nginx startup"

            sleep 15



            #############################################
            # Initial SSL Certificate Bootstrap
            #############################################

            DOMAIN="resilientbeing.online"

            CERT_PATH="./certbot/conf/live/$DOMAIN/fullchain.pem"



            if [ ! -f "$CERT_PATH" ]; then


              echo "No SSL certificate found."

              echo "Requesting initial Let's Encrypt certificate..."



              sudo docker compose run --rm certbot certonly \
                --webroot \
                --webroot-path=/var/www/certbot \
                -d "$DOMAIN" \
                --agree-tos \
                --register-unsafely-without-email \
                --non-interactive



              echo "Certificate created."

              echo "Restarting nginx to load certificate."



              sudo docker compose restart nginx



            else


              echo "SSL certificate already exists."

              echo "Skipping certificate generation."


            fi




            #############################################
            # Cleanup
            #############################################

            sudo docker image prune -f



            echo "Deployment completed successfully."
